version: 2.1

orbs:
  psyplot: psyplot/psyplot-ci-orb@1.5.12
  mattermost-plugin-notify: nathanaelhoun/mattermost-plugin-notify@1.2.0

executors:
  default: psyplot/default
  macos: psyplot/macos

parameters:
  unit-test-executor:
    description: Executor for the unit tests. Can be default or macos
    type: string
    default: default
  deploy-release:
    description: Deploy the comment as a new release to github and pypi
    type: boolean
    default: false

workflows:
  build-and-test:
    unless: << pipeline.parameters.deploy-release >>
    jobs:
      - psyplot/install-and-build:
          exec_environment: << pipeline.parameters.unit-test-executor >>
          setup_env: true
          build_args: "--build-only"
      - psyplot/test-parallel:
          name: test-xarray-latest
          parallelism: 2
      - psyplot/test-parallel:
          name: test-xarray-0.17
          parallelism: 2
          packages: xarray=0.17
      - mattermost-plugin-notify/approval-notification:
          name: notify-deploy
          context: mattermost
          message: >-
            Hello @all! A workflow on https://app.circleci.com/pipelines/github/psyplot/psyplot is awaiting your approval.
            Please check the uploaded docs and builds prior to approval.
          requires:
            - test-xarray-latest
            - test-xarray-0.17
      - hold-for-deploy:
          type: approval
          requires:
            - notify-deploy
      - psyplot/deploy-pkg:
          exec_environment: << pipeline.parameters.unit-test-executor >>
          context: anaconda
          requires:
            - hold-for-deploy
      - psyplot/deploy-docs:
          fingerprint: "fc:e3:0f:d0:c6:5a:6a:a5:0e:7c:d6:47:37:48:dd:67"
          requires:
            - hold-for-deploy
          filters:
            branches:
              only: main
      - psyplot/trigger-release-workflow:
          context: trigger-release
          filters:
            branches:
              only: main
          requires:
            - psyplot/deploy-pkg
            - psyplot/deploy-docs
  publish-release:
    when: << pipeline.parameters.deploy-release >>
    jobs:
      - psyplot/create-tag:
          ssh-fingerprints: "fc:e3:0f:d0:c6:5a:6a:a5:0e:7c:d6:47:37:48:dd:67"
          context: psyplot-admin
          user-name: psyplot-admin
          publish-release: true
          publish-version-tag: true
          requires:
            - psyplot/check-for-release
      - mattermost-plugin-notify/approval-notification:
          name: notify-release
          context: mattermost
          message: >-
            Hello @all! A new release has been created at https://github.com/psyplot/psyplot/releases.
            Please review it carefully, publish it and approve the upload to pypi.
          requires:
            - psyplot/create-tag
      - hold-for-pypi:
          type: approval
          requires:
            - notify-release
      - psyplot/deploy-pypi:
          context: pypi
          requires:
            - hold-for-pypi
          filters:
            branches:
              only: main
