version: 2.1

orbs:
  psyplot: psyplot/psyplot-ci-orb@1.5.4

workflows:
  build-and-test:
    jobs:
      - psyplot/install-and-build:
          setup_env: false
      - psyplot/deploy-docs:
          fingerprint: "fc:e3:0f:d0:c6:5a:6a:a5:0e:7c:d6:47:37:48:dd:67"
          requires:
            - psyplot/install-and-build
