{% set name = "psyplot" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  git_url: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY') }}{% if environ.get("BUILD_STR_END") %}_{{ environ.get("BUILD_STR_END") }}{% endif %}
  script: python -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
  - psyplot = psyplot.__main__:main
  - psyplot-plugin = psyplot.plugin_template:main
  skip: true  # [py == 27]

requirements:
  host:
  - python
  - pip
  run:
  - python >=3.6
  - docrep >=0.3
  - matplotlib
  - funcargparse
  - xarray
  - pyyaml

test:
  requires:
    - pytest
    - codecov
    - pytest-cov >=2.6.1
    - pyqt  # [osx]
    - netcdf4
    - dask
    - scipy
    # HACK: solve inconsistensies with libwebp
    # this should be removed when
    # https://github.com/conda-forge/libwebp-feedstock/issues/26
    # is solved
    - libtiff <4.1.0  # [osx]
  source_files:
    - tests
  commands:
    - psyplot --help
    - psyplot-plugin --help
    - pytest -v --cov={{ name|lower }}
    - codecov
  imports:
    - psyplot
    - psyplot.gdal_store
    - psyplot.compat
    - psyplot.config
    - psyplot.sphinxext

about:
  home: https://github.com/psyplot/psyplot
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Python package for interactive data visualization

  description: |
    psyplot is an cross-platform open source python project that mainly
    combines the plotting utilities of matplotlib and the data management of
    the xarray package and integrates them into a software that can be used via
    command-line and via a GUI.
  doc_url: http://psyplot.github.io
  dev_url: https://github.com/psyplot/psyplot
