name: psyplot_docs
channels:
    - local
    - psyplot/label/master
    - chilipp/label/conda-forge
dependencies:
    - python>3.6
    - dask
    - netCDF4
    - seaborn
    - sphinx_rtd_theme
    - ipython
    - sphinx
    - psy-maps
    - autodocsumm
    - pip
    - pip:
        - cdo
        - sphinx-argparse
