name: psyplot_docs
channels:
    - local
    - psyplot/label/master
    - chilipp/label/conda-forge
dependencies:
    - python>3.6
    - dask
    - xarray
    - netCDF4
    - matplotlib=3.2  # mainly for matplotlib compatibility
    - seaborn
    - sphinx_rtd_theme
    - ipython
    - nbconvert
    - jupyter_client
    - ipykernel
    - sphinx
    - psy-maps
    - pip
    - pip:
        - autodocsumm
        - cdo
        - sphinx-argparse
        - sphinx-nbexamples
